spring:
  application:
    name: multi-db-demo
  datasource:
    url: "jdbc:postgresql://10.0.0.20:5432/multi_db_test?currentSchema=cluster_1"
    username: "kurenai"
    password: "test"
    hikari:
      username: "kurenai"
      password: "test"
      jdbc-url: "jdbc:postgresql://10.0.0.20:5432/multi_db_test?currentSchema=cluster_1"
    cluster1:
      url: "jdbc:postgresql://10.0.0.20:5432/multi_db_test?currentSchema=cluster_1"
      username: "kurenai"
      password: "test"
    cluster2:
      url: "jdbc:postgresql://10.0.0.20:5432/multi_db_test?currentSchema=cluster_2"
      username: "kurenai"
      password: "test"
  jpa:
    open-in-view: false

ds:
  url: "jdbc:postgresql://10.0.0.20:5432/multi_db_test?currentSchema=cluster_1"
  username: "kurenai"
  password: "test"
logging:
  level:
    "org.springframework.data": trace
    root: info
    sql: debug

